project_name: gh-sub-issues

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-sub-issues
    main: ./main.go
    binary: gh-sub-issues
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/yahsan2/gh-sub-issues/cmd.Version={{.Tag}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: yahsan2
    name: gh-sub-issues