name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v ./...
      
    - name: Run tests with coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Build binary
      run: go build -v -o gh-sub-issues .
      
    - name: Verify binary
      run: ./gh-sub-issues --version
      
  integration:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Run integration tests
      run: |
        chmod +x test_integration.sh
        ./test_integration.sh